[workspace]
name = "chemparseplot"
version = "0.0.2"
description = "Parsers and plotting tools for computational chemistry."
authors = ["Rohit Goswami <rgoswami[at]ieee[dot]org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.12"

[pypi-dependencies]
rgpycrumbs = { git = "https://github.com/HaoZeke/rgpycrumbs", editable = true }
